### PR TITLE
make footer date dynamic

### PR DESCRIPTION
**Pull request by 0APOCALYPSE0**
### Description
This pull request fixes the dynamic footer year issue. The year in the footer now updates automatically, ensuring it remains current without manual intervention.

### Changes Made
- Added JavaScript to dynamically update the footer year.

### Motivation
Keeping the footer year updated enhances the user experience and maintains the website’s professional appearance.

### Testing
Tested on multiple browsers to ensure compatibility and correct year display.

### Checklist
- [x] Code follows the project’s guidelines
- [x] All tests pass
- [x] No new warnings are introduced

### Additional Notes
Looking forward to contributing more to this project! 😊

Thanks,
Aakash

### CODE REVIEW

**Comment by 0APOCALYPSE0** [comment]
Hey, I notice one more thing in your repository's About section.

image

Hacktoberfest tag spelling is incorrect. Please correct it otherwise this contribution may not count under Hacktoberfest

Thanks

**Comment by Shu12388y** [comment]
@0APOCALYPSE0 Mention Your issue number

**Comment by 0APOCALYPSE0** [comment]
it is resolving issue #77

**Comment by Shu12388y** [comment]
@0APOCALYPSE0  we don't need this feature right now

**Pull request closed without merging**
