### PR TITLE
added cron job api to send email to registered user about new blogs published

### LINKED ISSUE #65: Add a cron job api that send email to the register user about the new blogs published
### ISSUE NAME

Add a cron job api that send email to the register user about the new blogs published  

### ISSUE DESCRIPTION

Here are the docs https://vercel.com/docs/cron-jobs
Every Wednesday mail every signup user about the new blogs

### PR DESCRIPTION
**Pull request by shashi-sah2003**
fixes #65 
I have added 2 files
1. vercel.json configuration file lets you configure, and override the default behavior of Vercel from within your project. 
2. sendEmail.ts which sends email to all the registered users about the new blogs published every wednesday

### CODE REVIEW

**Review by Shu12388y — CHANGES_REQUESTED** [review]
Remove the vercel.json for now we also have to implement a pub- sub model. For now, remove the vercel.json  otherwise application will crash in prod

**Comment by shashi-sah2003** [comment]
image
@Shu12388y not able to commit new changes due to the above error 
do you want me to raise the issue for this and resolve this error then try to recommit this above PR again?

**Comment by Shu12388y** [comment]
@shashi-sah2003 let me resolve the error

**Comment by Shu12388y** [comment]
@shashi-sah2003 pull the code and try

**Pull request merged**
