### PR TITLE
Update page.tsx

### PR DESCRIPTION
**Pull request by Amansingh0807**
Moved setDisabled(false) inside the else block in the useEffect so it's only called when the email includes "@gmail".

### CODE REVIEW

**Comment by Shu12388y** [comment]
@Amansingh0807 Please mention the issue number

**Comment by Amansingh0807** [comment]
> @Amansingh0807 Please mention the issue number



> @Amansingh0807 Please mention the issue number

**Comment by Amansingh0807** [comment]
> @Amansingh0807 Please mention the issue number

issue number is #45

**Comment by Amansingh0807** [comment]
sorry this is done by mistake

**Comment by Amansingh0807** [comment]
sorry i did it by mistake

**Pull request closed without merging**
