### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Megh2005**
Updated The Readme File as per issue number **[14](https://github.com/Lets-code-with-us/scamwebsiteV1/issues/14)**

### CODE REVIEW

**Comment by Megh2005** [comment]
assign this to me with relevant tags

**Comment by Megh2005** [comment]
Hey @Shu12388y 
assign this to me with relevant tags

**Review by Shu12388y — COMMENTED** [review]
Please attach the screenshot of the readme output

**Comment by Shu12388y** [comment]
@Megh2005 Attach the screenshot of the readme. I will merge your PR

**Comment by Megh2005** [comment]
As soon as you merge the pr , the changes will get reflected in the main readme 

If you think that, it is not proper, you can revert it back

**Comment by Megh2005** [comment]
Please remove the `under review` lavel and assign the PR to me

**Pull request merged**
